name: icapps_license
description: Dart tool to generate a file that contains all licenses of the third party libraries
version: 1.0.1
homepage: https://github.com/icapps/flutter-icapps-license

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.0
  path: ^1.8.0
  yaml: ^3.1.0

dev_dependencies:
  test: ^1.16.5
